name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: junior-cook
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"
