name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snake generator
        uses: Platane/snk@v3
        with:
          github_user_name: junior-cook

      - name: List files for debugging
        run: ls -al

      - name: Show SVG preview for debugging
        run: head github-contribution-grid-snake.svg || echo "SVG not generated"

      - name: Commit and push SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: Generate snake animation
          add: github-contribution-grid-snake.svg
